config/routes.rb
Rails.application.routes.draw do
  #get 'votes/create'

  resources :stories do
    resources :votes
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
  validates :name, :link, presence: true
  has_many :votes do
    def latest
      order('id DESC').limit(5)
    end
  end
  
  def to_param
    "#{id}-#{name.gsub(/\W/, '-').downcase}"
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :story
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @current_time = Time.now
    @story = Story.order('RANDOM()').first
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)
    if @story.save
      flash[:notice] = 'Successfully submitted'
      redirect_to stories_path
    else
      render action: 'new'
    end
  end

  def show
    @story = Story.find(params[:id])
  end

  private
  def story_params
    params.require(:story).permit(:name, :link)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @story = Story.find(params[:story_id])
    @story.votes.create
    respond_to do |format|
      format.html { redirect_to @story, notice: 'Vote was counted' }
      #format.js {} #couldn't get this to properly render -- revisit later
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Ninja Learning Site</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id = "content">
        <h1> Interesting Links</h1>
        <% unless flash[:notice].blank? %>
        <div id= "notification"><%= flash[:notice] %></div>
        <% end %>
        <%= yield %>
    </div>
  </body>
</html>

app/views/stories/index.html.erb
<%= @current_time %>
<br></br>
A random link:
<%= link_to @story.name, @story%>

app/views/stories/new.html.erb
<% if @story.errors.any? %>
  <div class= "form errors">
    <h3> Errors </h3>
    <ul>
      <% @story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @story do |f| %>
  <div>
      <p><%= f.label :name %></p>
      <%= f.text_field :name %>
  </div>
  <div>
    <p><%= f.label :link %></p>
    <%= f.text_field :link %>
  </div>
  <%= submit_tag %>
<% end %>

app/views/stories/show.html.erb
<h2>
  <span id="vote_score">
    Score: <%=@story.votes.size %>
  </span>
  <%= @story.name %>
</h2>

<ul id= 'vote_history'>
  <% if @story.votes.empty? %>
    <em>No votes yet</em>
  <% else %>
    <%= render partial: 'votes/vote', collection: @story.votes.latest %>
  <% end %>
</ul>
<p>
  <%= link_to @story.link, @story.link %>
</p>
<div id="vote_form">
  <%= form_for [ @story, Vote.new ], remote: true do |f| %>
    <%= f.submit 'Vote for it' %>
  <% end %>
</div>
<!--
  <%= form_tag story_votes_path(@story), remote: true do %>
    <%= submit_tag 'Vote for this story' %>
  <% end %>
</div>
-->

app/views/votes/_vote.html.erb
<li><%= vote.created_at.to_formatted_s(:short) %><li>

app/views/votes/create.html.erb
<h1>Votes#create</h1>
<p>Find me in app/views/votes/create.html.erb</p>

app/views/votes/create.js.erb
$('#vote_score').html('Score: ' + <%= @story.votes.size %>)
$('#vote_score').css({backgroundColor: '#ffffcc'});

setTimeout(function(){
  $('vote_score').css({backgoundColor: '#ffffff'});
}, 2000);